services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto:/mosquitto/config         # <— dir mount (includes passwd)
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

