#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Barkasse Hub — Security & Persistence Setup
# ─────────────────────────────────────────────────────────────────────────────
# This script:
#   1. Generates a self-signed TLS CA + server certificate
#   2. Configures Mosquitto with TLS (8883) + password authentication
#   3. Installs InfluxDB 2.x for persistent time-series storage
#   4. Secures the Node-RED editor with adminAuth (bcrypt password)
#   5. Enables HTTPS on Node-RED (port 8443)
#
# Usage:
#   ./scripts/setup-security.sh
#
# You will be prompted for passwords if not set via environment variables:
#   MQTT_USER        (default: barkasse)
#   MQTT_PASS        (prompted if empty)
#   NODERED_PASS     (prompted if empty; for admin user in Node-RED editor)
#   INFLUX_PASS      (prompted if empty; for InfluxDB admin)
#   INFLUX_ORG       (default: barkasse)
#   INFLUX_BUCKET    (default: sensors)
#   TLS_DAYS         (default: 3650 = 10 years)
#   TLS_CN           (default: barkasse.local)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CERT_DIR="$REPO_DIR/certs"
MOSQUITTO_CONF="$REPO_DIR/mosquitto/mosquitto.conf"
MOSQUITTO_PWFILE="$REPO_DIR/mosquitto/passwd"
NODERED_DIR="/home/hub/.node-red"

# ── Defaults ──
MQTT_USER="${MQTT_USER:-barkasse}"
INFLUX_ORG="${INFLUX_ORG:-barkasse}"
INFLUX_BUCKET="${INFLUX_BUCKET:-sensors}"
TLS_DAYS="${TLS_DAYS:-3650}"
TLS_CN="${TLS_CN:-barkasse.local}"

if [[ "$EUID" -eq 0 ]]; then
  echo "Run this as the normal user (it will use sudo when needed)." >&2
  exit 1
fi

# ── Prompt for secrets ──
if [[ -z "${MQTT_PASS:-}" ]]; then
  echo -n "MQTT password for user '$MQTT_USER': "
  read -rs MQTT_PASS; echo
fi
if [[ -z "${NODERED_PASS:-}" ]]; then
  echo -n "Node-RED editor password (admin user): "
  read -rs NODERED_PASS; echo
fi
if [[ -z "${INFLUX_PASS:-}" ]]; then
  echo -n "InfluxDB admin password: "
  read -rs INFLUX_PASS; echo
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Barkasse Security Setup"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ═══════════════════════════════════════════════════════════════════════════════
# 1) TLS CERTIFICATES
# ═══════════════════════════════════════════════════════════════════════════════
echo "[1/5] Generating TLS certificates..."

mkdir -p "$CERT_DIR"

if [[ -f "$CERT_DIR/server.crt" && -f "$CERT_DIR/server.key" ]]; then
  echo "  Certificates already exist in $CERT_DIR — skipping."
  echo "  Delete $CERT_DIR/server.crt to regenerate."
else
  # Private CA
  openssl genrsa -out "$CERT_DIR/ca.key" 4096 2>/dev/null
  openssl req -x509 -new -nodes \
    -key "$CERT_DIR/ca.key" \
    -sha256 -days "$TLS_DAYS" \
    -subj "/C=DE/ST=Niedersachsen/O=Barkasse/CN=Barkasse CA" \
    -out "$CERT_DIR/ca.crt" 2>/dev/null

  # Server key + CSR
  openssl genrsa -out "$CERT_DIR/server.key" 2048 2>/dev/null

  # SAN config for localhost + LAN + Tailscale
  cat > "$CERT_DIR/server-san.cnf" <<SANEOF
[req]
distinguished_name = req_dn
req_extensions     = v3_req
prompt             = no

[req_dn]
C  = DE
ST = Niedersachsen
O  = Barkasse
CN = ${TLS_CN}

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = ${TLS_CN}
DNS.2 = localhost
DNS.3 = barkasse
IP.1  = 127.0.0.1
IP.2  = 192.168.10.10
IP.3  = ::1
SANEOF

  openssl req -new \
    -key "$CERT_DIR/server.key" \
    -config "$CERT_DIR/server-san.cnf" \
    -out "$CERT_DIR/server.csr" 2>/dev/null

  openssl x509 -req \
    -in "$CERT_DIR/server.csr" \
    -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" -CAcreateserial \
    -sha256 -days "$TLS_DAYS" \
    -extensions v3_req -extfile "$CERT_DIR/server-san.cnf" \
    -out "$CERT_DIR/server.crt" 2>/dev/null

  # Clean up
  rm -f "$CERT_DIR/server.csr" "$CERT_DIR/server-san.cnf" "$CERT_DIR/ca.srl"

  # Set permissions
  chmod 644 "$CERT_DIR/ca.crt" "$CERT_DIR/server.crt"
  chmod 600 "$CERT_DIR/ca.key" "$CERT_DIR/server.key"

  echo "  ✓ CA:   $CERT_DIR/ca.crt"
  echo "  ✓ Cert: $CERT_DIR/server.crt"
  echo "  ✓ Key:  $CERT_DIR/server.key"
fi


# ═══════════════════════════════════════════════════════════════════════════════
# 2) MOSQUITTO — TLS + PASSWORD AUTH
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "[2/5] Configuring Mosquitto (TLS + authentication)..."

# Generate password file
mosquitto_passwd -b -c "$MOSQUITTO_PWFILE" "$MQTT_USER" "$MQTT_PASS"
chmod 600 "$MOSQUITTO_PWFILE"

# Write config for both plain (LAN) and TLS
cat > "$MOSQUITTO_CONF" <<MQCONF
# ─── Barkasse Mosquitto Configuration ───
# Generated by setup-security.sh — do not edit manually.

# Disable anonymous access
allow_anonymous false
password_file /etc/mosquitto/barkasse_passwd

# ─── Listener 1: Plain MQTT on localhost only ───
# (for Node-RED and local services that communicate over loopback)
listener 1883 127.0.0.1
protocol mqtt

# ─── Listener 2: MQTT over TLS (all interfaces) ───
# (for ESP32 sensors and remote MQTT clients on the LAN)
listener 8883
protocol mqtt
cafile   /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile  /etc/mosquitto/certs/server.key
tls_version tlsv1.2

# Persistence
persistence true
persistence_location /var/lib/mosquitto/
autosave_interval 60
MQCONF

echo "  ✓ Password file: $MOSQUITTO_PWFILE"
echo "  ✓ Config:        $MOSQUITTO_CONF"

# Deploy to system
sudo install -m 0644 "$MOSQUITTO_CONF" /etc/mosquitto/conf.d/barkasse.conf
sudo install -m 0600 "$MOSQUITTO_PWFILE" /etc/mosquitto/barkasse_passwd
sudo chown mosquitto:mosquitto /etc/mosquitto/barkasse_passwd

# Deploy TLS certs for Mosquitto
sudo install -d -m 0755 /etc/mosquitto/certs
sudo install -m 0644 "$CERT_DIR/ca.crt"     /etc/mosquitto/certs/ca.crt
sudo install -m 0644 "$CERT_DIR/server.crt"  /etc/mosquitto/certs/server.crt
sudo install -m 0600 "$CERT_DIR/server.key"  /etc/mosquitto/certs/server.key
sudo chown mosquitto:mosquitto /etc/mosquitto/certs/server.key

echo "  ✓ Deployed to /etc/mosquitto/"


# ═══════════════════════════════════════════════════════════════════════════════
# 3) INFLUXDB 2.x
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "[3/5] Installing InfluxDB 2.x..."

if command -v influx &>/dev/null; then
  echo "  InfluxDB CLI already installed."
else
  # Add InfluxData repo
  if [[ ! -f /etc/apt/sources.list.d/influxdata.list ]]; then
    curl -fsSL https://repos.influxdata.com/influxdata-archive.key \
      | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata.gpg >/dev/null
    echo "deb [signed-by=/etc/apt/trusted.gpg.d/influxdata.gpg] https://repos.influxdata.com/debian stable main" \
      | sudo tee /etc/apt/sources.list.d/influxdata.list >/dev/null
    sudo apt-get update -qq
  fi
  sudo apt-get install -y -qq influxdb2
fi

sudo systemctl enable --now influxdb

# Wait for InfluxDB to start
echo "  Waiting for InfluxDB..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:8086/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

# Initial setup (idempotent — if already set up, skip)
if influx org list --host http://localhost:8086 2>/dev/null | grep -q "$INFLUX_ORG"; then
  echo "  InfluxDB already configured for org '$INFLUX_ORG'."
else
  influx setup \
    --host http://localhost:8086 \
    --org "$INFLUX_ORG" \
    --bucket "$INFLUX_BUCKET" \
    --username admin \
    --password "$INFLUX_PASS" \
    --retention 0 \
    --force
  echo "  ✓ InfluxDB setup complete (org=$INFLUX_ORG, bucket=$INFLUX_BUCKET)"
fi

# Save the token for Node-RED
INFLUX_TOKEN="$(influx auth list --host http://localhost:8086 --json 2>/dev/null | node -e "
const d=require('fs').readFileSync('/dev/stdin','utf8');
try{const a=JSON.parse(d); const t=a.find(x=>x.description&&x.description.includes('token')); console.log(t?t.token:a[0].token);}
catch(e){console.log('');}
" 2>/dev/null || echo "")"

if [[ -z "$INFLUX_TOKEN" ]]; then
  echo "  ⚠ Could not auto-detect InfluxDB token."
  echo "  Run: influx auth list --host http://localhost:8086"
  echo "  Then set INFLUX_TOKEN in Node-RED settings manually."
else
  echo "  ✓ InfluxDB token: ${INFLUX_TOKEN:0:10}..."
fi

# Configure retention policy for long-term storage
influx bucket update \
  --host http://localhost:8086 \
  --name "$INFLUX_BUCKET" \
  --retention 0 2>/dev/null || true

echo "  ✓ Bucket '$INFLUX_BUCKET' set to infinite retention"


# ═══════════════════════════════════════════════════════════════════════════════
# 4) NODE-RED — ADMIN AUTH + HTTPS
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "[4/4] Securing Node-RED editor + enabling HTTPS..."

# Install bcryptjs for password hashing
cd "$NODERED_DIR"
npm install --save bcryptjs 2>/dev/null || npm install bcryptjs 2>/dev/null

# Install node-red-contrib-influxdb for InfluxDB integration
npm install --save node-red-contrib-influxdb 2>/dev/null

# Generate bcrypt hash
ADMIN_HASH=$(node -e "
  const bcrypt = require('bcryptjs');
  const hash = bcrypt.hashSync(process.argv[1], 10);
  console.log(hash);
" "$NODERED_PASS")

echo "  ✓ bcrypt hash generated for admin"

# Write the updated settings.js
cat > "$NODERED_DIR/settings.js" <<'SETTINGSEOF'
// settings.js — Barkasse Hub (secured)
// Generated by setup-security.sh

const path = require('path');
const fs   = require('fs');
const bcrypt = require('bcryptjs');

// TLS certificates
const CERT_DIR = path.join(__dirname, '..', 'barkasse-hub', 'certs');
let httpsOptions = null;
try {
    httpsOptions = {
        key:  fs.readFileSync(path.join(CERT_DIR, 'server.key')),
        cert: fs.readFileSync(path.join(CERT_DIR, 'server.crt')),
        ca:   fs.readFileSync(path.join(CERT_DIR, 'ca.crt'))
    };
} catch (e) {
    console.warn('TLS certs not found — running without HTTPS:', e.message);
}

module.exports = {
    /***************************************************************************
     * Flow file / userdir
     ***************************************************************************/
    flowFile: 'flows.json',
    flowFilePretty: true,

    /***************************************************************************
     * Server — HTTPS
     ***************************************************************************/
    uiPort: process.env.PORT || 8443,
    https: httpsOptions,

    // Also listen on 8080 for local HTTP (Chromium kiosk on localhost)
    // Node-RED doesn't support dual ports natively, so we redirect in code below.

    // Editor at /admin
    httpAdminRoot: '/admin',

    // HTTP-In nodes (e.g. /history, /debug/stats) at /
    httpNodeRoot: '/',

    // Static UI from repo
    httpStatic: path.join(__dirname, '..', 'barkasse-hub', 'ui'),

    /***************************************************************************
     * Authentication — Node-RED Editor
     ***************************************************************************/
    adminAuth: {
        type: "credentials",
        users: [{
            username: "admin",
            password: "ADMIN_HASH_PLACEHOLDER",
            permissions: "*"
        }],
        default: {
            permissions: "read"
        }
    },

    /***************************************************************************
     * Context storage — Persistent (file-backed)
     ***************************************************************************/
    contextStorage: {
        default: {
            module: "localfilesystem",
            config: {
                dir:       path.join(__dirname, 'context'),
                flushInterval: 30
            }
        },
        memory: {
            module: "memory"
        }
    },

    /***************************************************************************
     * Runtime / Logging
     ***************************************************************************/
    diagnostics: {
        enabled: true,
        ui: true,
    },

    runtimeState: {
        enabled: false,
        ui: false,
    },

    logging: {
        console: {
            level: "info",
            metrics: false,
            audit: false
        }
    },

    /***************************************************************************
     * Editor
     ***************************************************************************/
    editorTheme: {
        projects: { enabled: false, workflow: { mode: "manual" } },
        codeEditor: { lib: "monaco", options: {} },
        markdownEditor: { mermaid: { enabled: true } },
        multiplayer: { enabled: false }
    },

    /***************************************************************************
     * Node settings
     ***************************************************************************/
    functionExternalModules: true,
    globalFunctionTimeout: 0,
    functionTimeout: 0,
    functionGlobalContext: {},
    debugMaxLength: 1000,
    mqttReconnectTime: 15000,
    serialReconnectTime: 15000,
    inboundWebSocketTimeout: 5000,
};
SETTINGSEOF

# Inject the actual hash (sed-safe)
ESCAPED_HASH=$(printf '%s\n' "$ADMIN_HASH" | sed -e 's/[\/&]/\\&/g')
sed -i "s/ADMIN_HASH_PLACEHOLDER/$ESCAPED_HASH/" "$NODERED_DIR/settings.js"

echo "  ✓ settings.js updated with adminAuth + HTTPS + contextStorage"


# ═══════════════════════════════════════════════════════════════════════════════
# DEPLOY & RESTART
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "Restarting services..."

sudo systemctl daemon-reload

# Mosquitto
sudo systemctl restart mosquitto
if systemctl is-active --quiet mosquitto; then
  echo "  ✓ Mosquitto restarted (port 1883 localhost + 8883 TLS)"
else
  echo "  ✗ Mosquitto failed to start — check: journalctl -u mosquitto"
fi

# Node-RED
sudo systemctl restart barkasse-ui.service
sleep 3
if systemctl is-active --quiet barkasse-ui.service; then
  echo "  ✓ Node-RED restarted (HTTPS on port 8443)"
else
  echo "  ✗ Node-RED failed to start — check: journalctl -u barkasse-ui"
fi

# Remove old redirect service if present
sudo systemctl disable --now barkasse-http-redirect.service 2>/dev/null || true
sudo rm -f /etc/systemd/system/barkasse-http-redirect.service

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Setup complete!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  MQTT (local):  mqtt://127.0.0.1:1883 (user=$MQTT_USER)"
echo "  MQTT (TLS):    mqtts://0.0.0.0:8883  (user=$MQTT_USER)"
echo "  Node-RED UI:   https://localhost:8443/"
echo "  Node-RED Edit: https://localhost:8443/admin (user=admin)"
echo "  InfluxDB:      http://localhost:8086/"
echo ""
echo "  CA cert for clients: $CERT_DIR/ca.crt"
echo "  Copy ca.crt to ESP32/clients for TLS verification."
echo ""
if [[ -n "${INFLUX_TOKEN:-}" ]]; then
  echo "  InfluxDB Token: $INFLUX_TOKEN"
  echo "  (Save this — needed for Node-RED influxdb nodes)"
  echo ""
fi
echo "  To test MQTT:"
echo "    mosquitto_pub -h 127.0.0.1 -p 1883 -u $MQTT_USER -P '***' -t test -m hello"
echo "    mosquitto_sub -h 127.0.0.1 -p 8883 --cafile $CERT_DIR/ca.crt -u $MQTT_USER -P '***' -t test"
echo ""
